-- General
require('keymaps')
require('options')
require('colors')

-- Plugins
require('plugins/packer')
require('plugins/coc')
require('plugins/bufferline')
require('plugins/lualine')
require('plugins/gitsigns')
require('plugins/indent-blankline')
require('plugins/nvim-autopairs')
require('plugins/nvim-cmp')
require('plugins/nvim-colorizer')
require('plugins/nvim-comment')
require('plugins/nvim-scrollbar')
require('plugins/nvim-search-and-replace')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
require('plugins/project')
require('plugins/telescope')
require('plugins/toggleterm')
require('plugins/vim-multi-cursor')

